name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.0
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: rfcm83
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: rfcm83/demodockeractions
        tags: latest
