name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
    # Username used to log in to a Docker registry. If not set then no login will occur
        username: rfcm83
    # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    # Docker repository to tag the image with
        repository: rfcm83/demodockeractions
    # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest
